[package]
name = "jackbox-custom-content"
version = "2.0.0"
edition = "2021"
build="src/build/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.7.3", package = "gtk4", features = ["v4_12"]}
# TODO: Remove if gtk gets update with these new macros? Mostly looking for derived_properties for easier use.
# glib-macros = "0.18.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
open = "5"

[build-dependencies]
glib-build-tools = "0.17.0"
regex = "1.10.2"