[package]
name = "jackbox-custom-content"
version = "2.0.0"
edition = "2021"
build="src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.5.5", package = "gtk4"}
serde_json = "1.0"

[build-dependencies]
glib-build-tools = "0.17.0"